# Generated by Django 6.0 on 2025-12-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название урока', max_length=250)),
                ('started_at', models.DateTimeField(help_text='Начало урока')),
                ('duration', models.PositiveSmallIntegerField(
                    choices=[(45, '45 минут'), (90, '90 минут')],
                    default=45,
                    help_text='Продолжительность урока в минутах',
                )),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
